require("settings")
require("ui.diag_float")
require("filetypes")
require("keymaps")
require("plugins")

require("lsp")
require("keyd")
require("tabline")
require("format").attach()
require("plugins.treesitter").setup()
