require("trouble").setup({})

vim.keymap.set("n", "<leader>tt", function()
	require("trouble").toggle()
end, { desc = "Toggle trouble" })
vim.keymap.set("n", "<leader>tw", function()
	require("trouble").toggle("workspace_diagnostics")
end, { desc = "Workspace diagnostics" })
vim.keymap.set("n", "<leader>td", function()
	require("trouble").toggle("document_diagnostics")
end, { desc = "Document diagnostics" })
vim.keymap.set("n", "<leader>tq", function()
	require("trouble").toggle("quickfix")
end, { desc = "Quickfix list" })
vim.keymap.set("n", "<leader>tl", function()
	require("trouble").toggle("loclist")
end, { desc = "Loclist" })
vim.keymap.set("n", "gd", function()
	require("trouble").toggle("lsp_definitions")
end, { desc = "LSP definitions" })
vim.keymap.set("n", "gi", function()
	require("trouble").toggle("lsp_implementations")
end, { desc = "LSP implementations" })
vim.keymap.set("n", "gr", function()
	require("trouble").toggle("lsp_references")
end, { desc = "LSP references" })
