local map = require("util").map

require("trouble").setup({})

map("n", "<leader>tt", function()
	require("trouble").toggle()
end, { desc = "Toggle trouble" })
map("n", "<leader>tw", function()
	require("trouble").toggle("workspace_diagnostics")
end, { desc = "Workspace diagnostics" })
map("n", "<leader>td", function()
	require("trouble").toggle("document_diagnostics")
end, { desc = "Document diagnostics" })
map("n", "<leader>tq", function()
	require("trouble").toggle("quickfix")
end, { desc = "Quickfix list" })
map("n", "<leader>tl", function()
	require("trouble").toggle("loclist")
end, { desc = "Loclist" })
map("n", "gd", function()
	require("trouble").toggle("lsp_definitions")
end, { desc = "LSP definitions" })
