local h = require("tests.harness")
local tf = require("util.textfield")

h.test("insert appends and advances the caret", function()
	local text, caret = tf.insert("ab", 2, "c")
	h.eq(text, "abc")
	h.eq(caret, 3)
end)

h.test("insert splices at the caret", function()
	local text, caret = tf.insert("abc", 1, "X")
	h.eq(text, "aXbc")
	h.eq(caret, 2)
end)

h.test("insert handles multibyte", function()
	local text, caret = tf.insert("ab", 1, "é")
	h.eq(text, "aéb")
	h.eq(caret, 2)
	h.eq(tf.len("aéb"), 3)
end)

h.test("caret is clamped", function()
	local text, caret = tf.insert("ab", 99, "c")
	h.eq(text, "abc")
	h.eq(caret, 3)
end)

h.test("backspace deletes before the caret", function()
	local text, caret = tf.backspace("abc", 2)
	h.eq(text, "ac")
	h.eq(caret, 1)
	h.eq(tf.backspace("abc", 0), "abc")
end)

h.test("delete removes at the caret", function()
	local text, caret = tf.delete("abc", 1)
	h.eq(text, "ac")
	h.eq(caret, 1)
	local same, c = tf.delete("abc", 3)
	h.eq(same, "abc")
	h.eq(c, 3)
end)

h.test("delete_word removes the word before the caret", function()
	local text, caret = tf.delete_word("foo bar", 7)
	h.eq(text, "foo")
	h.eq(caret, 3)

	local t2, c2 = tf.delete_word("foo bar", 3)
	h.eq(t2, " bar")
	h.eq(c2, 0)

	local t3 = tf.delete_word("abc", 3)
	h.eq(t3, "")
end)
