local h = require("tests.harness")
local keymap = require("loupe.keymap")
local config = require("loupe.config")

h.test("canonical equates <C-s> and <C-S>", function()
	h.eq(keymap.canonical("<C-s>"), keymap.canonical("<C-S>"))
	h.eq(keymap.canonical("<C-s>"), "<C-S>")
end)

h.test("canonical leaves printable keys alone", function()
	h.eq(keymap.canonical("r"), "r")
	h.eq(keymap.canonical("<Space>"), "<Space>")
	h.eq(keymap.canonical("<lt>"), "<lt>")
end)

h.test("build canonicalizes lhs and drops unbinds", function()
	local map = keymap.build({ ["<C-s>"] = "split", ["<C-X>"] = false, ["q"] = 12 })
	h.eq(map["<C-S>"], "split")
	h.eq(map["<C-X>"], nil)
	h.eq(map["q"], nil)
end)

h.test("resolve maps every context", function()
	local maps = keymap.resolve(config.defaults.mappings)
	h.eq(maps.browse["<CR>"], "open")
	h.eq(maps.browse["<C-O>"], "sources")
	h.eq(maps.menu["r"], "rename")
	h.eq(maps.sources["b"], "buffers")
	h.eq(maps.prompt["<CR>"], "submit")
	h.eq(maps.prompt["<C-U>"], "clear")
end)

h.test("resolve tolerates a missing mappings table", function()
	local maps = keymap.resolve(nil)
	h.eq(maps.browse, {})
	h.eq(maps.menu, {})
	h.eq(maps.sources, {})
	h.eq(maps.prompt, {})
end)
